### PR TITLE
- fixes microsoft translation by providing api region

### PR DESCRIPTION
**Pull request by baywet**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] I have read the [CONTRIBUTING](https://github.com/fabasoad/translation-action/CONTRIBUTING.md) doc.
- [x] Tests for the changes have been added (for bug fixes / features).
- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features).
- [ ] Build (`npm run build`) was run locally and any changes were pushed.
- [x] Tests (`npm test`) has passed locally and any fixes were made for failures.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Microsoft made providing the region with the key mandatory as outlined [here](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-reference#authenticating-with-a-regional-resource) this pull request allows subscribers to specify their region so the call to the API works
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Note: unit tests are currently failing in the PR validation because PRs from forks don't have access to secrets for security reasons.

### CODE REVIEW

**Comment by baywet** [comment]
CC @fabasoad

**Comment by fabasoad** [comment]
Thank you @baywet for this PR! Didn't have a chance to review it yet but I'll do my best to take a look at it tomorrow 🙂

**Comment by fabasoad** [comment]
@baywet Thank you for contribution!

**Comment by baywet** [comment]
thanks for merging!

**Pull request merged**
